### ISSUE TITLE
Filter out bosh_job ~ compilation* in alerts

### ISSUE THREAD

**Issue by bodymindarts** [cloudfoundry-community/prometheus-boshrelease#1]
The alert BOSHJobEphemeralDiskWillFillIn2Hours is firing during compilation due to the compilation workers.

**Comment by bodymindarts** [comment]
Or perhaps this should be configured via the alertmanager

**Comment by frodenas** [comment]
Nice catch @bodymindarts. I will fix it at the alert rules by excluding the compilation jobs.

**Comment by frodenas** [comment]
This should be fixed by commit https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/8a8fda1a14d5fa2c2baab0915316f570b3cc8b87. I'll leave this issue open until I cut I new final release.

**Comment by frodenas** [comment]
This is fixed as [v9](https://github.com/cloudfoundry-community/prometheus-boshrelease/releases/tag/v9).
