### ISSUE TITLE
Prometheus Benchmark Dashboard

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-community/prometheus-boshrelease#104]
While deploying prometheus bosh release on a large (~200vms) deployment, we met scraping performance issues.
Theses dashboards was incredibly usefull to identify and fix :

https://grafana.com/dashboards/2078 
http://demo.robustperception.io:3000/dashboard/db/prometheus-benchmark-1-6-x?refresh=1m&orgId=1 

It could be a usefull addition to the built-in dashboard
cc @ArthurHlt

**Comment by frodenas** [comment]
@poblin-orange Most of those dashboards are already at the [prometheus_dashboards](https://github.com/cloudfoundry-community/prometheus-boshrelease/tree/master/jobs/prometheus_dashboards/templates) job. Is there any particular dashboard that is missing and you find it useful?

**Comment by frodenas** [comment]
I've refactored (https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/cee17053584f96bba8ebc6dafb87b441c65e7daf) the `Prometheus: Storage` dashboard to include some of the missing panels. 

Please reopen (or contribute via PR) if there's any other panel you want to see.

**Comment by poblin-orange** [comment]
@thks +1:
