### ISSUE TITLE
Prometheus API can respond but Prometheus WebUI can't do.

### ISSUE THREAD

**Issue by kkitai** [cloudfoundry-community/prometheus-boshrelease#105]
Hi.

Although I did setup prometheus-17.6.0 with bosh, I couldn't get data from prometheus webui(no data points).
but Prometheus API is working.

```
$ curl -g 'http://100.99.50.80:9090/api/v1/series?match[]=cf_organization_info{environment="hoge"}'
{"status":"success","data":[{"__name__":"cf_organization_info","deployment":"cf","environment":"hoge","instance":"localhost:9193","job":"cf","organization_id":"e00539b9-4437-4e88-9a9a-6b807861383c","organization_name":"org","quota_name":"default"},
...
..
.
```

Why would it happen?

**Comment by frodenas** [comment]
Is there anything suspicious at the prometheus logs? or at your browser console? seems weird that prometheus  api is able to show you data but the ui is not.

**Comment by kkitai** [comment]
@frodenas 

oddly enough, i can see data from webui when i check again today. I still don't know why It is not able to show at yesterday. 

However, there wan't suspicious message in prometheus log and  console.

**Comment by frodenas** [comment]
ok, glad to hear is fixed now. Please reopen if it happens again.
