### ISSUE TITLE
Alertmanager Configuration

### ISSUE THREAD

**Issue by benjaminguttmann-avtq** [cloudfoundry-community/prometheus-boshrelease#108]
Hi,

I am currently facing an issue with configuring the Alertmanager I am not quite sure if it is a bug or if I am getting something wrong:

I am using an external_url, e.g. http://someurl/my/alertmanager for the alertmanager but when prometheus tries to trigger an alert it uses 'alertmanagerIP:9093/api/v1/alerts'.
When I 'curl http://alertmanagerIP:9093/my/alertmanager/api/v1/alerts' I got a 200 for 'curl http://alertmanagerIP:9093/api/v1/alerts' I got a 404. 
Afterwards I added the route_prefix (/my/alertmanger) to the alertmanager properties. I can see in the prometheus  is started with - alertmanager.url="alertmanagerIP:9093/my/alertmanager" but then I am running into the issue that I got a 404 for 'curl http://alertmanagerIP:9093/my/alertmanager/api/v1/alerts' because now it is 'curl http://alertmanagerIP:9093/my/alertmanager/my/alertmanager/api/v1/alerts'. Seems a bit confusing to me.

I also tried to configure a path_prefix via [prometheus.alerting.alertmanagers.path_prefix ](https://prometheus.io/docs/operating/configuration/#<alertmanager_config>) but it seems like this is not added to the url as well. 

Perhaps someone can tell me if it is a bug or a feature ;-)

Thanks.

**Comment by frodenas** [comment]
The alertmanager `external_url` property should NOT have a path, instead, it should be configured using the `route_prefix` property:

```
properties:
  alertmanager:
    web:
      external_url: http://someurl
      route_prefix: /my/alertmanager
```

Prometheus them will [add](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/jobs/prometheus/templates/bin/prometheus_ctl#L33) the `route_prefix` when invoking the alertmanager API.
