### ISSUE TITLE
Bosh v2 style manifest

### ISSUE THREAD

**Issue by marcus-sds** [cloudfoundry-community/prometheus-boshrelease#109]
Hi..
Is there Bosh v2 style manifest?

**Comment by frodenas** [comment]
The [README](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/README.md) contains instructions using BOSH CLI v2. Manifests are located at the [manifests](https://github.com/cloudfoundry-community/prometheus-boshrelease/tree/master/manifests) directory.
