### ISSUE TITLE
Add libfontconfig

### ISSUE THREAD

**Issue by mkuratczyk** [cloudfoundry-community/prometheus-boshrelease#111]
Hey,

Grafana package installs PhantomJS (/var/vcap/packages/grafana/vendor/phantomjs) which is dynamically linked with libfontconfig that is not present on the stemcell. This makes it impossible to use Grafana's Direct Link Rendered Image feature (http://docs.grafana.org/reference/sharing/#direct-link-rendered-image). Simple 'apt-get install libfontconfig' solves the problem but I'm not sure how to properly fix that in the bosh release.

**Comment by frodenas** [comment]
Solved at https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/5b489c7c39204f2a7c90be3dc0277515f75cda94.

**Comment by mkuratczyk** [comment]
Thanks a lot!
