### ISSUE TITLE
Apps: System Dashboard's 'buildpack' panel consume too much space.

### ISSUE THREAD

**Issue by kukgini** [cloudfoundry-community/prometheus-boshrelease#113]
After upgrade to : v18.5.0 , When buildpack comes from github like this: 
```
container-certificate-trust-store=2.1.0_RELEASE java-buildpack=v3.16-https://github.com/cloudfoundry/java-buildpack.git#2110750 java-main open-jdk-like-jre=1.8.0_141 open-jdk-like-memory-calculator=2.0.2_RELEASE spring-auto-reconfiguration=1.12.0_RELEASE
```
It consumes too much window space.

**Comment by frodenas** [comment]
Good catch @kukgini! I've removed that panel (https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/f502d2fd17cb442fb94468fa13d34f0752de1031) as there isn't any way we can truncate the buildpack name in grafana. I will readd it later if I find a proper way to show it without breaking the dashboard.
