### ISSUE TITLE
Prometheus_datasource.erb

### ISSUE THREAD

**Issue by stu-pete** [cloudfoundry-community/prometheus-boshrelease#114]
Hi,

I'm probably doing something wrong in another place, but since I can't figure it out here goes my question:

Im trying to deploy the release and everything actually works fine. Except that the grafana job on the grafana vm does not start properly because the post start script fails. I tried debugging and looked into the files on my machines..

the spec.ip injection either works in a way I do not understand or it misses "p('')" around spec.ip.

This is the template:
GRAFANA_DATASOURCES_API="<%= p('grafana.server.protocol', 'http') %>://<%= spec.ip %>:<%= p('grafana.server.http_port') %>/api/datasources"
this is how it ends up on my machine:

GRAFANA_DATASOURCES_API="http://:3000/api/datasources"

What am I doing wrong?

**Comment by frodenas** [comment]
what bosh version are you using? `spec.ip` was introduced at [v258](https://github.com/cloudfoundry/bosh/releases/tag/v258)

**Comment by stu-pete** [comment]
Thx, this was the reason! i deployed against an old test environment. I will update the director and retry!
