### ISSUE TITLE
cadvisor needs execution permission.

### ISSUE THREAD

**Issue by kukgini** [cloudfoundry-community/prometheus-boshrelease#117]
When I deploy v18.5.0 with bosh cli v2 with manifest/operators/monitor-cadvisor.yml, I got this:
```
06:02:44 | Updating instance prometheus: prometheus/182378f0-fc70-42dd-a670-cd0c80d42f97 (0) (canary) (00:05:02)
            L Error: 'prometheus/0 (182378f0-fc70-42dd-a670-cd0c80d42f97)' is not running after update. Review logs for failed jobs: cadvisor
```

Detail process log is here:
/var/vcap/sys/log/cadvisor/cadvisor.stderr.log
```
/var/vcap/jobs/cadvisor/bin/cadvisor_ctl: line 22: /var/vcap/packages/cadvisor/bin/cadvisor: Permission denied
```
And actually cadvisor has no execution permission.
```
# ls -al /var/vcap/packages/cadvisor/bin/cadvisor
-rw-r--r-- 1 root root 23203876 Jul  1 15:33 /var/vcap/packages/cadvisor/bin/cadvisor
```

**Comment by frodenas** [comment]
Thanks for reporting this bug. Fixed at commit https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/20acabeba014e66b29adb955598359058d0bbbf4.
