### ISSUE TITLE
too many close_wait with bosh exporter

### ISSUE THREAD

**Issue by marcus-sds** [cloudfoundry-community/prometheus-boshrelease#119]
We are using 18.2.0 version release and there is too many "close wait" socket issue with bosh exporter.  
prometheus/5defa4ca-eb77-48ce-a5e0-1eb47adcd5f3:/var/vcap/packages# netstat -an|grep 25555|grep CLOSE|wc -l
742
prometheus/5defa4ca-eb77-48ce-a5e0-1eb47adcd5f3:~# netstat -an|grep 25555|grep CLOSE|wc -l
743

**Comment by frodenas** [comment]
Are there any errors at the `bosh_exporter` logs (`/var/vcap/sys/log/bosh_exporter/`)? I just checked my environments and I don't see any leaked connection, so my guess is that when an error happens talking to the director, there's a tcp connection (or a body read) that is not closed properly.

**Comment by marcus-sds** [comment]
After the below logs, we started to get the "too many open files" messages.
time="2017-09-03T06:11:00Z" level=error msg="Error while reading deployments: Finding deployments: Performing request GET 'https://10.10.0.6:25555/deployments': Performing GET request: Refreshing token: UAA responded with non-successful status code '401' response '{\"error\":\"invalid_token\",\"error_description\":\"The token has been revoked: 38e92d9ab4e4498c98100733cbeb32ca-r\"}'" source="bosh_collector.go:167"
time="2017-09-03T06:13:00Z" level=error msg="Error while reading deployments: Finding deployments: Performing request GET 'https://10.10.0.6:25555/deployments': Performing GET request: Refreshing token: UAA responded with non-successful status code '401' response '{\"error\":\"invalid_token\",\"error_description\":\"The token has been revoked: 38e92d9ab4e4498c98100733cbeb32ca-r\"}'" source="bosh_collector.go:167"

2017/09/03 06:17:00 http: Accept error: accept tcp 0.0.0.0:9190: accept4: too many open files; retrying in 5ms

**Comment by frodenas** [comment]
Thanks for the logs @marcus-sds.

I've upgraded the [bosh-utils](https://github.com/cloudfoundry/bosh-utils) library used by the `bosh_exporter`, as it's now more strict with tcp timeouts. I believe this will fix your issue. I'll cut a new version of this release pretty soon with the new `bosh_exporter` version.

**Comment by frodenas** [comment]
@marcus-sds I ran several test revoking tokens, updating passwords and using a shorter` refresh_token_validity` to reproduce this. When using `bosh_exporter` [v2.4.4](https://github.com/cloudfoundry-community/bosh_exporter/releases/tag/v2.4.4) I can confirm that `CLOSE_WAIT` socket connections are dropped after 1 minute.

I'll wait to close this issue until I cut a new bosh release version.

**Comment by frodenas** [comment]
This has been fixed at [v18.6.0](https://github.com/cloudfoundry-community/prometheus-boshrelease/releases/tag/v18.6.0). Thanks for reporting this bug!

Besides the leaking connections problem, the `{"error":"invalid_token","error_description":"The token has been revoked"}` error happens when bosh is using uaa for authentication, and you're using a `username` and `password` for the `bosh_exporter`. The `bosh_cli` used to authenticate has a default `refresh_token_validity` of 1 day, so after that period, `bosh_exporter` will stop working. I recommend using a `client-id` and `client-secret` instead, by applying the [enable-bosh-uaa.yml](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/manifests/operators/enable-bosh-uaa.yml) ops file.

**Comment by frodenas** [comment]
@gerhard This is interesting, if BOSH is not using UAA, the returned error message does not make any sense. Are you sure the director is not configured with UAA? Is it possible that it's configured with UAA but you're using a username and password?

**Comment by gerhard** [comment]
You were right, the BOSH director was configured to use UAA, I was using a username and password. I managed to fix my issue, submitting a tiny PR that allows the UAA client id to be templated - it's currently hard-coded to `bosh_exporter`

Thanks!
