### ISSUE TITLE
ShieldJobFailed1d alert only triggers when job is paused

### ISSUE THREAD

**Issue by szaouam** [cloudfoundry-community/prometheus-boshrelease#122]
Hello,

My question is about the ShieldJobFailed1d  alert for shield.

The code bellow is for this alert.

==>

> ALERT ShieldJobFailed1d
>   IF shield_job_status == 4 and shield_job_paused != 0
> 

It may be better to change it to be run when getting a failed job that is not in a paused state.

==>

> ALERT ShieldJobFailed1d
>   IF shield_job_status == 4 and shield_job_paused != 1

Best regards,

**Comment by frodenas** [comment]
Thanks for reporting this @szaouam. It was a bug, it has been fixed at https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/619ea651ec032a115892a36d4e298e35406857f9.
