### ISSUE TITLE
Logs to stop / start all explorer are not in the right place

### ISSUE THREAD

**Issue by ldangeard-orange** [cloudfoundry-community/prometheus-boshrelease#123]
All explorer (mysql_explorer, node_explorer etc...) use **/blob/master/src/common/utils.sh**
Log create by MONIT are in **_/var/vcap/sys/log_** and not in **_/var/vcap/sys/log/< explorer >_**

It is necessary to correct the script util.sh en use ${LOG_DIR}
```
mkdir -p /var/vcap/sys/log

exec > >(tee -a >(logger -p user.info -t vcap.$(basename $0).stdout) | awk -W interactive '{ gsub(/\\n/, ""); system("echo -n [$(date +\"%Y-%m-%d %H:%M:%S%z\")]"); print " " $0 }' >>/var/vcap/sys/log/$(basename $0).log)
exec 2> >(tee -a >(logger -p user.error -t vcap.$(basename $0).stderr) | awk -W interactive '{ gsub(/\\n/, ""); system("echo -n [$(date +\"%Y-%m-%d %H:%M:%S%z\")]"); print " " $0 }' >>/var/vcap/sys/log/$(basename $0).err.log)

```

. with
```
mkdir -p ${LOG_DIR}

exec > >(tee -a >(logger -p user.info -t vcap.$(basename $0).stdout) | awk -W interactive '{ gsub(/\\n/, ""); system("echo -n [$(date +\"%Y-%m-%d %H:%M:%S%z\")]"); print " " $0 }' >>${LOG_DIR}/log/$(basename $0).log)
exec 2> >(tee -a >(logger -p user.error -t vcap.$(basename $0).stderr) | awk -W interactive '{ gsub(/\\n/, ""); system("echo -n [$(date +\"%Y-%m-%d %H:%M:%S%z\")]"); print " " $0 }' >>${LOG_DIR}/$(basename $0).err.log)
```

**Comment by frodenas** [comment]
There's a difference between control script logs and process logs. For process log, the general rule is to use `/var/vcap/sys/log/<process>`, but I don't believe there is one for the control script logs. Some examples:

* Uses `/var/vcap/sys/log`:
  * [cf-release](https://github.com/cloudfoundry/cf-release/blob/master/src/common/utils.sh#L4)
  * [loggregator](https://github.com/cloudfoundry/loggregator/blob/58f5d1c36fe0d8df23c4777f4d6a84cb3e812336/src/common/utils.sh#L4)
  * [uaa](https://github.com/cloudfoundry/uaa-release/blob/f13056298d1168ddf6b1d116966eb0ca846957e7/src/uaa_utils/utils.sh#L4)
* Uses `/var/vcap/sys/log/monit`:
  * [diego-release](https://github.com/cloudfoundry/diego-release/blob/develop/src/pid_utils.sh#L4)
* Uses `/var/vcap/sys/log/<process>`:
  * [etcd-release](https://github.com/cloudfoundry-incubator/etcd-release/blob/1670a2a01d0b721a99dd4e2e4e4132e4a631f935/jobs/etcd/templates/etcd_ctl.erb#L12)

In this release I'm using the most common directory being used at most releases: `/var/vcap/sys/log`, Is there any specific issue you want to solve by moving the logs to `/var/vcap/sys/log/<process>`?

**Comment by ldangeard-orange** [comment]
I'm use cf-mysql release  and logs in /var/vcap/sys/log are :
```
drwxr-x---  2 root root 4096 Sep 19 15:19 exporter-user/           
drwxr-xr-x  2 vcap vcap 4096 Sep 19 15:19 galera-healthcheck/      
drwxr-xr-x  2 vcap vcap 4096 Sep 19 15:19 gra-log-purger/          
drwxr-x---  2 root root 4096 Sep 19 15:17 login_banner/            
drwxr-x---  2 vcap vcap 4096 Sep 19 15:19 mysql/                   
drwxr-xr-x  2 root root 4096 Sep 19 15:19 mysqld_exporter/         
-rw-r--r--  1 root root 1856 Sep 21 08:50 mysqld_exporter_ctl.log
drwxr-xr-x  2 root root 4096 Sep 19 15:19 node_exporter/           
-rw-r--r--  1 root root  456 Sep 21 08:50 node_exporter_ctl.err.log
-rw-r--r--  1 root root  842 Sep 21 08:50 node_exporter_ctl.log
drwxr-x---  2 root root 4096 Sep 19 15:19 smoke-tests-user/        
```
either 

-  we move < processe_exporter>_ctl*.log in < processe_exporter>

either 

-  we move < processe_exporter>_ctl*.log in /var/vcap/sys/log/monit

it's more clean.

**Comment by frodenas** [comment]
UAA vm:

```
drwxr-x--- 9 root vcap  4096 Sep 20 16:14 .
drwxr-x--- 6 root vcap  4096 Sep 20 16:14 ..
drwxr-x--- 2 vcap vcap  4096 Sep 21 06:02 consul_agent
drwxr-xr-x 2 vcap vcap  4096 Sep 20 16:15 metron_agent
drwxr-xr-x 2 root root  4096 Sep 20 16:14 node_exporter
-rw-r--r-- 1 root root   228 Sep 21 06:03 node_exporter_ctl.err.log
-rw-r--r-- 1 root root   355 Sep 21 06:03 node_exporter_ctl.log
drwxr-x--- 2 vcap vcap  4096 Sep 20 16:14 route_registrar
drwxr-xr-x 2 vcap vcap  4096 Sep 20 16:14 statsd_injector
drwxr-xr-x 2 root root  4096 Sep 20 16:13 syslog_forwarder
drwxr-x--- 2 vcap vcap  4096 Sep 21 05:15 uaa
-rw-r--r-- 1 root root   360 Sep 21 06:03 uaa_ctl.err.log
-rw-r--r-- 1 root root 62415 Sep 21 06:03 uaa_ctl.log
```

**Comment by ldangeard-orange** [comment]
move `uaa_ctl.err.log` and` uaa_ctl.log` in `uaa`
and move `node_exporter_ctl.err.log`  and `node_exporter_ctl.log` in `node_exporter`
i's better to monitoring log

**Comment by ldangeard-orange** [comment]
Thank's
