### ISSUE TITLE
Migration from bosh v1 to bosh v2

### ISSUE THREAD

**Issue by eugenetolan** [cloudfoundry-community/prometheus-boshrelease#126]
Is there any progress on the documentation steps for migrating an existing promethues deployed using bosh v1 to using bosh-cli v2?

**Comment by frodenas** [comment]
@eugenetolan it should be pretty straightforward as far as you use the same deployment name and the names of the jobs have not changed. Bosh will just update the jobs with the new software. Is there anything that you're concerned about?

**Comment by eugenetolan** [comment]
@frodenas not particullary, I just wondered if there was any plans to document it. Will give it a go anyway, thanks!

**Comment by frodenas** [comment]
ok, I will keep this open in the meantime. I'd appreciate if you report back any issues. Thanks!

**Comment by frodenas** [comment]
@eugenetolan Did you upgraded your deployment to cli v2?

**Comment by eugenetolan** [comment]
yes I did!

**Comment by frodenas** [comment]
Thanks @eugenetolan.
