### ISSUE TITLE
Grafana 18.6.1 with UAA issue

### ISSUE THREAD

**Issue by gmadu123** [cloudfoundry-community/prometheus-boshrelease#127]
I am following exact documentation still i see below issues after i give oauth username and password.

Server side error :(
interface conversion: interface {} is nil, not string

**Comment by frodenas** [comment]
Where do you see that error?

**Comment by gmadu123** [comment]
In the Browser window

**Comment by gmadu123** [comment]
in the Grafana logs i see this

t=2017-09-25T15:10:13+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/login/generic_oauth status=500 remote_addr=10.234.66.107 time_ms=58 size=711 referer=https://login.system.us-chd1-ip01.1dc.com/login
t=2017-09-25T15:15:12+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/logout status=302 remote_addr=10.234.66.107 time_ms=58 size=29 referer="https://pcfmonitoring-chd-prod.1dc.com/?orgId=1"
t=2017-09-25T15:15:17+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/login/generic_oauth status=302 remote_addr=10.234.66.107 time_ms=59 size=306 referer=https://pcfmonitoring-chd-prod.1dc.com/login
t=2017-09-25T15:15:35+0000 lvl=eror msg="Request error" logger=context userId=1 orgId=1 uname=admin error="interface conversion: interface {} is nil, not string" stack="/usr/local/go/src/runtime/panic.go:489 (0x430e7f)\n/usr/local/go/src/runtime/iface.go:172 (0x413cd1)\n/go/src/github.com/grafana/grafana/pkg/api/login_oauth.go:73 (0xd8f3b2)\n/usr/local/go/src/runtime/asm_amd64.s:514 (0x45dc58)\n/usr/local/go/src/reflect/value.go:434 (0x4aeccf)\n/usr/local/go/src/reflect/value.go:302 (0x4ae294)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x78116f)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x780b3a)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79ee12)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x79ed36)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:14 (0xb41997)\n/usr/local/go/src/runtime/asm_amd64.s:514 (0x45dc58)\n/usr/local/go/src/reflect/value.go:434 (0x4aeccf)\n/usr/local/go/src/reflect/value.go:302 (0x4ae294)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x78116f)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x780b3a)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79ee12)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x79ed36)\n/go/src/github.com/grafana/grafana/pkg/middleware/session.go:79 (0xb41bdb)\n/usr/local/go/src/runtime/asm_amd64.s:514 (0x45dc58)\n/usr/local/go/src/reflect/value.go:434 (0x4aeccf)\n/usr/local/go/src/reflect/value.go:302 (0x4ae294)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x78116f)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x780b3a)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79ee12)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x79ed36)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:146 (0xb41901)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x79ebb1)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x780e42)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x780c3b)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79ee12)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x79ed36)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:33 (0xb3f262)\n/usr/local/go/src/runtime/asm_amd64.s:514 (0x45dc58)\n/usr/local/go/src/reflect/value.go:434 (0x4aeccf)\n/usr/local/go/src/reflect/value.go:302 (0x4ae294)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x78116f)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x780b3a)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79ee12)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x7b0c69)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:296 (0x7ab06d)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x7a38ec)\n/usr/local/go/src/net/http/server.go:2568 (0x68df12)\n/usr/local/go/src/net/http/server.go:1825 (0x68a2e2)\n/usr/local/go/src/runtime/asm_amd64.s:2197 (0x4603f1)\n"
t=2017-09-25T15:15:35+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/login/generic_oauth status=500 remote_addr=10.234.66.107 time_ms=57 size=711 referer=https://login.system.us-chd1-ip01.1dc.com/login

**Comment by frodenas** [comment]
can you please check the contents of the `/var/vcap/jobs/grafana/config/grafana.ini` file at the `grafana` vm? You will see a `[auth.generic_oauth]` section.

**Comment by gmadu123** [comment]
here is that content:
[auth.generic_oauth]

enabled = true



allow_sign_up = true



client_id = grafana



client_secret = xxxxx



scopes = openid



auth_url = https://login.system.us-chd1-ip01.1dc.com/oauth/authorize



token_url = https://login.system.us-chd1-ip01.1dc.com/oauth/token



api_url = https://login.system.us-chd1-ip01.1dc.com/userinfo







name = Cloud Foundry



tls_client_ca = /var/vcap/jobs/grafana/config/generic_oauth_tls_client_ca.pem
tls_client_cert = /var/vcap/jobs/grafana/config/generic_oauth_tls_client_cert.pem
tls_client_key = /var/vcap/jobs/grafana/config/generic_oauth_tls_client_key.pem

**Comment by frodenas** [comment]
interesting, what version of uaa are you using? (or pcf version?)

**Comment by gmadu123** [comment]
[svc-xadmpcf@r3pvtl001 prometheus-boshrelease-master]$ uaac version
UAA client 3.6.0

**Comment by gmadu123** [comment]
pcf version
PCF Ops Manager v1.10.9.0;

**Comment by frodenas** [comment]
Can you please check the `var/vcap/jobs/grafana/config/generic_oauth_tls_client_*.pem` files? Do they contain the right certificates?

PS: I'll try to reproduce this tonight on a PCF 1.10 environment.

**Comment by gmadu123** [comment]
i did not find certificates inside files. i see below content.

((uaa_ssl.private_key))

**Comment by gmadu123** [comment]
cert file shows this

((uaa_ssl.certificate))

I will try placing cert and private key by getting from uaa machine and test

**Comment by gmadu123** [comment]
Tried. Same error.

**Comment by frodenas** [comment]
Have you restarted grafana?

**Comment by gmadu123** [comment]
yes. i did by sitting in grafana and did monit stop and monit start

**Comment by gmadu123** [comment]
did i do any wrong?

**Comment by gmadu123** [comment]
When i tried install. I followed below command. Any wrong with command why the cert file did not install properly? The way i am passing below command to pick certs is wrong? or is this suppose to work?

bosh -e bosh-concourse -d prometheus deploy manifests/prometheus.yml --vars-store tmp/deployment-vars.yml -o manifests/operators/monitor-bosh.yml -v bosh_url=https://xx.xxx.xx.xx -v bosh_username=xxxxx -v bosh_password=xxxxxxxxxxxxxxxxxxxxx --var-file bosh_ca_cert=./ca.crt -v metrics_environment=chandler_prod_prometheus -o manifests/operators/monitor-cf.yml -v system_domain=system.us-chd1-ip01.1dc.com -v uaa_clients_cf_exporter_secret=xxxxxx -v uaa_clients_firehose_exporter_secret=xxxxxxx -v traffic_controller_external_port=9186 -v skip_ssl_verify=true -o manifests/operators/enable-grafana-uaa.yml -v uaa_clients_grafana_secret=xxxxxx --var-file uaa_ssl.ca=./ca.crt --var-file uaa_ssl.certificate=./uaa.crt --var-file uaa_ssl.private_key=./uaa_private.crt

**Comment by frodenas** [comment]
What version of `bosh-cli` are you using (`bosh -v`)? dotted variables (like `uaa_ssl.ca`) are only supported when using  `bosh-cli` >= [v2.0.27](https://github.com/cloudfoundry/bosh-cli/releases/tag/v2.0.27).

Also, did you updated the `ca` as well? I just rant a test on both pcf 1.10 & pcf 1.11 without any problems.

**Comment by gmadu123** [comment]
Here is bosh version
bosh -version
version 2.0.23-a5bb0df-2017-05-31T21:21:01Z

**Comment by gmadu123** [comment]
The above command and syntax is correct? I mean if i give ./filename for cert it will take?

**Comment by frodenas** [comment]
Yes, the syntax is correct, but you need to upgrade your bosh cli.

**Comment by gmadu123** [comment]
I upgraded bosh-cli and ran command to update grafana vm with cert files. still i am getting same error

bosh --version
version 2.0.40-9fc1ea4-2017-09-18T23:00:15Z

Succeeded

**Comment by gmadu123** [comment]
is it possible to have screen share session?

**Comment by frodenas** [comment]
ok, but have you checked if the 3 `var/vcap/jobs/grafana/config/generic_oauth_tls_client_*.pem` files contains now the right certificates?

**Comment by gmadu123** [comment]
Hi, I have verified and all certs looks good but i still see the error

Server side error :(
login.OAuthLogin(get info from generic_oauth)

**Comment by frodenas** [comment]
Are you still experiencing problems with this? One of your teammates told me at the Slack channel that the certificates were not a problem anymore, but that you still were having problems with `scopes`?

**Comment by frodenas** [comment]
@gmadu123 Are you still experiencing problems with this?

**Comment by frodenas** [comment]
Please reopen if the problem still persists.

**Comment by gmadu123** [comment]
we dont have any issues. we resolved the issue. Now our prometheus can able to use UAA
