### ISSUE TITLE
bosh prometheus deploy

### ISSUE THREAD

**Issue by gmadu123** [cloudfoundry-community/prometheus-boshrelease#129]
I am trying to deploy bosh prometheus deploy. I need clarity on below syntax. Below i see -o syntaxes 2 but dont have any -v parameters with any paswords. Is the below syntax am i missing anything from the doc? Please provide me some example. I am trying to hook pcf bosh1 director content  to bosh2 director prometheus deploy dashboards.  

If you have configured your bosh-deployment to use UAA user management (via the uaa.yml ops file) we recommend adding the add-bosh-exporter-uaa-clients.yml op file to your bosh-deployment and then adding the enable-bosh-uaa.yml ops file to the prometheus deployment by running the following command (filling the required variables with your own values):

bosh -d prometheus deploy manifests/prometheus.yml \
  --vars-store tmp/deployment-vars.yml \
  -o manifests/operators/monitor-bosh.yml \
  -o manifests/operators/enable-bosh-uaa.yml \
  -v bosh_url= \
  --var-file bosh_ca_cert= \
  -v metrics_environment=

**Comment by frodenas** [comment]
When you add the [add-bosh-exporter-uaa-clients.yml](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/manifests/operators/bosh/add-bosh-exporter-uaa-clients.yml) op file to your bosh deployment it will create a [bosh_exporter](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/manifests/operators/bosh/add-bosh-exporter-uaa-clients.yml#L5) client id with a randomly generated [secret](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/manifests/operators/bosh/add-bosh-exporter-uaa-clients.yml#L16). Then the [enable-bosh-uaa.yml](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/manifests/operators/enable-bosh-uaa.yml) will use that `bosh_exporter` client id and secret (via the previously generated [uaa_bosh_exporter_client_secret](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/manifests/operators/enable-bosh-uaa.yml#L10) variable).

I recommend you reading the [Explicit declaration](http://bosh.io/docs/cli-int.html#explicit) section at the [CLI Variable Interpolation](http://bosh.io/docs/cli-int.html#variables) docs.

**Comment by gmadu123** [comment]
When you add the add-bosh-exporter-uaa-clients.yml op file to your bosh deployment it will create a bosh_exporter client id with a randomly generated secret

May i know which bosh deployment? I have bosh deployment for PCF platform and i have separate bosh director for prometheus and concourse

**Comment by frodenas** [comment]
The [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) github repo. In your case, the one you used to deploy the bosh director for concourse and prometheus.
