### ISSUE TITLE
LDAP support for grafana

### ISSUE THREAD

**Issue by Murryy79** [cloudfoundry-community/prometheus-boshrelease#131]
Is there plans to package  default ldap configurations(ldap.toml file) for grafana web login in next release?

**Comment by frodenas** [comment]
There're already [properties](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/jobs/grafana/spec#L320) to set up LDAP authentication. An example:

```
grafana:
  auth:
    ldap:
      enabled: true
      config: |
        # Set to true to log user information returned from LDAP
        verbose_logging = false

        [[servers]]
        # Ldap server host (specify multiple hosts space separated)
        host = "REDACTED"
        # Default port is 389 or 636 if use_ssl = true
        port = 389
        # Set to true if ldap server supports TLS
        use_ssl = false
        # Set to true if connect ldap server with STARTTLS pattern (create connection in insecure, then upgrade to secure connection with TLS)
        start_tls = false
        # set to true if you want to skip ssl cert validation
        ssl_skip_verify = false
        # set to the path to your root CA certificate or leave unset to use system defaults
        # root_ca_cert = /path/to/certificate.crt

        # Search user bind dn
        bind_dn = "REDACTED"
        # Search user bind password
        # If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""
        bind_password = "REDACTED"

        # User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
        search_filter = "REDACTED"

        # An array of base dns to search through
        search_base_dns = ["REDACTED"]

        # In POSIX LDAP schemas, without memberOf attribute a secondary query must be made for groups.
        # This is done by enabling group_search_filter below. You must also set member_of= "cn"
        # in [servers.attributes] below.

        ## Group search filter, to retrieve the groups of which the user is a member (only set if memberOf attribute is not available)
        # group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
        ## An array of the base DNs to search through for groups. Typically uses ou=groups
        # group_search_base_dns = ["REDACTED"]

        # Specify names of the ldap attributes your ldap uses
        [servers.attributes]
        #name = "givenName"
        #surname = "sn"
        #username = "cn"
        #member_of = "memberOf"
        #email =  "mail"

        [[servers.group_mappings]]
        # If you want to match all (or no ldap groups) then you can use wildcard
        group_dn = "*"
        org_role = "Viewer"
```

**Comment by Murryy79** [comment]
I have already seen this and have implemented. However, I was looking for
this file ldap.toml to be packaged in the release (prometheus-*.tar.gz)

We currently after deploying the release, SSH to grafana VM and manually
create this file. Or we could extract prometheus-*.tar.gz, add ldap.toml
and repackage before uploading release to bosh.

The concern is when re-deploying ldap configuration will be lost and have
to redo.

These manual steps makes our automation complicated.
Thanks

**Comment by frodenas** [comment]
I don't understand why you're ssh'ing into the VM in order to create this file. If you specify the properties at your deployment manifest, then at deployment time, the file will be automatically created and filled with your LDAP configuration.

**Comment by Murryy79** [comment]
Thanks for your quick response. I always wanted to add ldap configuration
into manifest.

 What I don't know is to write manifest with properties that fill up a
particular file in intended path in a vm. I am fairly new to writing
manifest in YAML for bosh deployment. Reaserching tutorials on the web.

I just thought packaging default ldap configuration file with the release
and then users fill up their enterprise ldap parameters using manifest.

Thanks again.

On Oct 2, 2017 8:15 AM, "Ferran Rodenas" <notifications@github.com> wrote:

I don't understand why you're ssh'ing into the VM in order to create this
file. If you specify the properties at your deployment manifest, then at
deployment time, the file will be automatically created and filled with
your LDAP configuration.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cloudfoundry-community/prometheus-boshrelease/issues/131#issuecomment-333530816>,
or mute the thread

**Comment by Murryy79** [comment]
@frodenas Thanks for ldap configuration example. I was able to stick that in my manifest. Only question is how do I pass ldap certificate itself to the path I provide here # root_ca_cert = /path/to/certificate.crt. 

I tried a couple different ways but no luck.

 root_ca_cert : |
                       -----BEGIN CERTIFICATE-----
                       -----END CERTIFICATE------
or 
 root_ca_cert = |
                       -----BEGIN CERTIFICATE-----
                       -----END CERTIFICATE------

**Comment by frodenas** [comment]
The actual release does NOT allow passing a LDAP CA certificate. Is this a problem in your current environment? Can you contact your LDAP server NOT using TLS? if this is a problem, please open a new issue and I'll try to make it configurable.
