### ISSUE TITLE
bosh exporter file descriptor issues

### ISSUE THREAD

**Issue by marcus-sds** [cloudfoundry-community/prometheus-boshrelease#134]
Hi, still we have file descriptor issues with bosh_exporter. The version is prometheus/18.6.2.
1. lsof result exceeds limit : 1027
2. monit restart bosh_exporter
3. lsof check
prometheus/d32d13ce-5802-461c-9a1c-f442e3716b0b:/var/vcap/jobs/bosh_exporter/packages# lsof -p 22086|wc -l
9
prometheus/d32d13ce-5802-461c-9a1c-f442e3716b0b:/var/vcap/jobs/bosh_exporter/packages# lsof -p 22086|wc -l
24
prometheus/d32d13ce-5802-461c-9a1c-f442e3716b0b:/var/vcap/jobs/bosh_exporter/packages# lsof -p 22086|wc -l
19
prometheus/d32d13ce-5802-461c-9a1c-f442e3716b0b:/var/vcap/jobs/bosh_exporter/packages# lsof -p 22086|wc -l
17
prometheus/d32d13ce-5802-461c-9a1c-f442e3716b0b:/var/vcap/jobs/bosh_exporter/packages# lsof -p 22086|wc -l
25
4. netstat result
netstat -an|grep 9190|wc -l
1

========== error log
2017/10/19 13:02:52 http: Accept error: accept tcp 0.0.0.0:9190: accept4: too many open files; retrying in 320ms
2017/10/19 13:02:52 http: Accept error: accept tcp 0.0.0.0:9190: accept4: too many open files; retrying in 640ms
2017/10/19 13:02:53 http: Accept error: accept tcp 0.0.0.0:9190: accept4: too many open files; retrying in 1s
2017/10/19 13:02:54 http: Accept error: accept tcp 0.0.0.0:9190: accept4: too many open files; retrying in 1s
time="2017-10-19T13:02:54Z" level=error msg="Error while reading deployments: Finding deployments: Performing request GET 'https://10.10.0.6:25555/deployments': Performing GET request: Retry: Get https://10.10.0.6:25555/deployments: dial tcp 10.10.0.6:25555: socket: too many open files" source="bosh_collector.go:167"

**Comment by peterellisjones** [comment]
We're also seeing the same issue on 19.01

https://github.com/cloudfoundry-community/bosh_exporter/issues/14

**Comment by marcus-sds** [comment]
With workaround, I added cron release opsfile like below.

- type: replace
  path: /instance_groups/name=prometheus/jobs/-
  value:
    name: cron
    release: cron
    properties:
      cron:
        variables:
          PATH: /var/vcap/package/mypackage/bin:/bin:/sbin:/usr/sbin:/usr/bin:/usr/local/bin
        entries:
        - command: /var/vcap/bosh/bin/monit restart bosh_exporter
          minute: '59'
          hour: '15'
          day: '*'
          month: '*'
          wday: '*'
          user: root
        - command: /var/vcap/bosh/bin/monit restart cf_exporter
          minute: '59'
          hour: '15'
          day: '*'
          month: '*'
          wday: '*'
          user: root

- type: replace
  path: /releases/-
  value:
    name: cron
    version: "latest"

**Comment by frodenas** [comment]
Let's track this at https://github.com/bosh-prometheus/bosh_exporter/issues/14.
