### ISSUE TITLE
UAA Authentication fails with error: login.OAuthLogin(NewTransportWithCode)

### ISSUE THREAD

**Issue by vChrisR** [cloudfoundry-community/prometheus-boshrelease#137]
This happened after upgrading from version 18.6.2 to 19.0.0. 
UAA auth worked fine before 19.0.0

I used the enable-grafana-uaa.yml operator. 

Error from the log: msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="Post https://login.<redacted>/oauth/token: x509: certificate signed by unknown authority"

allready checked the CA and it's there in /etc/ssl/certs so should be trusted.

**Comment by frodenas** [comment]
@vChrisR Seems the latest grafana version switched from not verifying the TLS client cert to verify it. Can you please do a quick test updating your [enable-grafana-uaa.yml](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/manifests/operators/enable-grafana-uaa.yml) and adding `tls_skip_verify_insecure: true` at the bottom?

**Comment by vChrisR** [comment]
@frodenas adding that line to the yaml didn't do anything.
However: manually adding it to grafana.ini and restarting grafana fixed the problem.

**Comment by frodenas** [comment]
My fault, I forgot that there's no property at the `grafana` job to pick up that value. Thanks for testing it manually. https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/822694248d559e528172b176fdb3cd12aee3dd6d should fix that.

**Comment by frodenas** [comment]
Shipped at [v19.0.1](https://github.com/cloudfoundry-community/prometheus-boshrelease/releases/tag/v19.0.1).
