### ISSUE TITLE
Enhancement of documentation

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry-community/prometheus-boshrelease#16]
Hi,
I am currently trying to install prometheus-boshrelease on OS CF, backed by OpenStack. The deployment went through smoothly after creating a OS deployment manifest, I am able to open Grafana, but I am not able:
- to see the dashboards provided
- when importing the dashboards manually, any datapoints

So it seems, that I am doing something wrong. Could any give me heads up? I would also participate creating the documentation.

Thanks a lot & BR,
Johannes

**Comment by mkuratczyk** [comment]
Hi Johannes,

A few things to start with:
- if Prometheus is running go to prometheus:9090 (or nginx:9090) and in the Targets menu check if you have any targets defined and whether they are up
- check if you can manually get metrics from your exporters (curl http://exporter-IP:PORT/metrics)

If you want to automatically deploy the dashboards you can take a look at my sample manifest: https://github.com/mkuratczyk/prometheus-on-PCF/blob/master/prometheus.yml#L52-L77 (I don't know if there is a way without listing all dashboard files explicitly - would like to know as well). If you have done that and still don't see the dashboards in Grafana after 'bosh deploy' then check whether /var/vcap/jobs/grafana/bin/prometheus-dashboards script on your Grafana VM has been rendered correctly (as you can see here https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/jobs/grafana/templates/bin/prometheus-dashboards it will be almost empty unless the template renders properly to generate the content).

**Comment by frodenas** [comment]
@jhiemer The default templates are pretty basic right now and does not include the proper jobs to monitor CF. I still need to work on the documentation, but I don't yet consider this release ready, so I'm waiting until I finish some more features, and then I'll proceed with the docs.

In the meantime, I suggest following @mkuratczyk advice and even using his manifest file as an example. His manifest contains all the proper bits to monitor CF.

@mkuratczyk You need to explicitly specify what dashboards you want to import into Grafana. The reason for this is that not all deployments are equal (ie, in one customer we are not using the `bosh_exporter`, we use the `graphite_exporter`, and the latter does not provide all the info; another example is the `mysql` dashboards, ...). I know this is painful, but I plan to improve this in next releases if I find the right solution :)

**Comment by frodenas** [comment]
@jhiemer Closing this. We can follow the status of the documentation effort at #2. But please feel free to reopen this issue or a new one if you face any problems when deploying the bosh release.
