### ISSUE TITLE
Metrics showing for a non-existent CF component after scale down

### ISSUE THREAD

**Issue by omearaj** [cloudfoundry-community/prometheus-boshrelease#17]
I scaled my routing tier to include 2 routers and then scaled back down to a single router to validate my dashboard settings and ability to add metrics as the platform changed. I noticed the second router is still showing in the dashboards. Using the prometheus graph tool and put in my query and it shows both routers. What can I look at to validate this behavior?

![screen shot 2016-12-02 at 10 08 44 am](https://cloud.githubusercontent.com/assets/1473334/20843291/043ba520-b878-11e6-9735-a801ee4e868e.png)
![screen shot 2016-12-02 at 10 14 10 am](https://cloud.githubusercontent.com/assets/1473334/20843314/1c671b8e-b878-11e6-9a92-dab67dda4c6e.png)

**Comment by frodenas** [comment]
Yes, this is due https://github.com/prometheus/prometheus/issues/398. if you wait between 5-10 mins, the datapoints from the deleted gorouter will disappear.

BTW, happens also with unhealthy job alerts (https://github.com/cloudfoundry-community/prometheus-boshrelease/issues/6).

**Comment by omearaj** [comment]
The component has been gone for days, late last week.

**Comment by frodenas** [comment]
@omearaj Apologies, my fault, I tested this and metrics from dead components are still returned. The firehose exported had a cache that never was expired. This should have been fixed at v12.2.0.

Please reopen if, after upgrading to v12.2.0, you still observe this behavior.
