### ISSUE TITLE
After upgrade from 12.0.0 to 12.2.0 graphs not showing deployment details

### ISSUE THREAD

**Issue by omearaj** [cloudfoundry-community/prometheus-boshrelease#18]
I upgrade to 12.2 and my graphs are not showing bosh deployment details.
![screen shot 2016-12-05 at 2 31 35 pm](https://cloud.githubusercontent.com/assets/1473334/20903200/b317ac70-baf7-11e6-839a-a7f25a38310e.png)

**Comment by omearaj** [comment]
BTW, prometheus looks correct. 
![screen shot 2016-12-05 at 2 34 47 pm](https://cloud.githubusercontent.com/assets/1473334/20903304/110dc38c-baf8-11e6-9b6f-5aaa10c62571.png)

**Comment by frodenas** [comment]
@omearaj Something is wrong with the labels. Is this a custom dashboard? or one that comes from the bosh release? The labels should be `bosh_job_name` and `bosh_job_index`, just look at the prometheus screenshot what labels are being returned.

**Comment by frodenas** [comment]
BTW, apologies if this is a custom dashboard :( I'm doing some breaking changes trying to find the right pattern for labels.

**Comment by omearaj** [comment]
Got it. Thanks
