### ISSUE TITLE
bosh_exporter should not filter.azs by default

### ISSUE THREAD

**Issue by mkuratczyk** [cloudfoundry-community/prometheus-boshrelease#19]
Hi,

What is the use case for the 'else' statement here: https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/jobs/bosh_exporter/templates/bin/bosh_exporter_ctl#L50-L51 ? We just ran into an issue where we had no job-level information after deploying prometheus-release and we tracked it down to this - we didn't intend to filter at all but by default it was filtering on AZ (and we didn't have any interesting jobs in that AZ).

Thanks,

**Comment by frodenas** [comment]
This is intended to simplify the deployment when using cloud config [azs](http://bosh.io/docs/azs.html) in an HA deployment (like the one outlined [here](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/docs/Deployment%20Topology.svg)).

By default, the `bosh_exporter` will track all deployment jobs that are deployed on the same `az` as the `bosh_exporter`. If you want to use a single `bosh_exporter` regardless of the `azs`, then you need to set the `bosh_exporter.filter.azs` property with all the `azs` you want to track.

Note also that if you don't have configured cloud-config `azs`, then the `bosh_exporter` should pick up all job deployments (as the `az` will be `blank`).

I'm curious about your deployment and why it didn't work for you. Do you have configured cloud-config `azs`? If yes, does the prometheus deployment specify `azs`?

**Comment by mkuratczyk** [comment]
In our case we have a PCF deployment with 3 AZs and a separate BOSH Director for deploying non-Pivotal releases. So Prometheus was getting data from PCF's Director but filtered for an AZ name from a completely different Director and therefore it was missing almost all data (only deployment information was available).

I understand your use case now. So the question is just whether the default should be suited for small deployments or large deployments. I'd personally argue that it should default to small deployments (and therefore no default filtering) simply because someone who is setting up a sophisticated topology like yours knows better whet they are doing (one would hope ;) ) and therefore understands what needs to be configured/filtered while someone who's just starting with Prometheus can fall into the trap like we did. In our case it was obvious because there was simply no data on a few dashboards but if I understand correctly, even with a single Director in a multi-AZ configuration by default you will only get data about one AZ. That could lead to users thinking they have their monitoring working (all dashboards have nice graphs) while in fact they would only be monitoring one AZ.

Thanks,

**Comment by frodenas** [comment]
I see, but I would argue that your use-case is not the typical small deployment use-case :)

Anyway, let me think if I can find a solution that can work easily on multiple scenarios.

**Comment by mkuratczyk** [comment]
Yes, two Directors is not a use case to optimize for. :)  But if I understand correctly, if you just have a normal single-Director deployment with 3 AZs configured and you deploy Prometheus, you will only have data from a third of your deployment and you'll need to look carefully to realize that. That's a relatively small deployment where the defaults deceive the user.

**Comment by frodenas** [comment]
Well, only if you deploy the prometheus release and use an `az` for the `bosh_exporter` job. Isn't it this case? (I've not tested this scenario)

**Comment by mkuratczyk** [comment]
I've not tried such a scenario yet either, but I'm not sure I follow - what do you mean by "use an az for the bosh_exporter job"?

**Comment by frodenas** [comment]
I mean that you prometheus deployment is using the `az` property for the job that contains the `bosh_exporter` template, otherwise, the `spec.az` should return an empty string.

**Comment by mkuratczyk** [comment]
Do you mean 'azs' as defined in https://bosh.io/docs/manifest-v2.html#instance-groups ? It is required so it will always be there...

**Comment by frodenas** [comment]
No if you are not using cloud config for this particular deployment (or not using cloud config at all, the simplest scenario). Bear in mind that you're using PCF/OpsMan, that handles (and hides) most of the manifest boilerplate for you via a tile, and that's not the common scenario outside of Pivotal deployments. 

But again, as I said in a previous comment, I'd like to find the right solution that handles several scenarios. Simplifying your use case by removing that default means making it more complex for other scenarios.

**Comment by mkuratczyk** [comment]
I'm still not sure we are talking about the same thing but I'll just try this scenario when I get a chance and probably then I'll understand. For the time being I'm ok to just explicitly filter for all our AZs, just wanted to understand why data is filtered by default which seemed counter-intuitive. Thanks,

**Comment by frodenas** [comment]
@mkuratczyk After reviewing your use case, I agree with you. Commit https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/367a816902cb6c812dfac43004a0cbc7270d0801 has fixed this, `azs` are not filtered by default, and must be explicitly set if someone wants to filter.
