### ISSUE TITLE
Create documentation on how to monitor BOSH and Cloud Foundry

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry-community/prometheus-boshrelease#2]

**Comment by rjain15** [comment]
+1 on documentation, I would like to contribute if you have raw notes to start with. I don't know how to configure it with the TSDB Nozzle, but if you have some notes, I can test and document.

**Comment by jhiemer** [comment]
+1 from my side as well. I have installed prometheus, but I can't see the exporter working for Bosh and the Firehose. What are the steps to configure them correctly?

**Comment by cppforlife** [comment]
+1 as well for more docs or nice integration with @dsabeti's https://github.com/cloudfoundry/cf-deployment

**Comment by frodenas** [comment]
A bit late :sweat_smile: but the [README](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/README.md) now contains proper documentation. It uses [BOSH CLI v2](https://bosh.io/docs/cli-v2.html) deployment instructions and [op files](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/README.md#operations-files) to integrate with [cf-deployment](https://github.com/cloudfoundry/cf-deployment) when required.
