### ISSUE TITLE
Add a warning regarding the `cf_exporter` resource consumption

### ISSUE THREAD

**Issue by janaurka** [cloudfoundry-community/prometheus-boshrelease#21]
The `cf_exporter` can slow down the `cloud_controller` dramatically when the `scrape_interval` has a low value.

**Comment by frodenas** [comment]
This has been fixed at [cf_exporter 0.4.6](https://github.com/cloudfoundry-community/cf_exporter/releases/tag/v0.4.6), as it doesn't use the `inline-relations-depth=2` param when scraping `Applications`. 

And here there's a probe, from 4s to 0.7s 😃 :

![screen shot 2017-02-25 at 00 52 13](https://cloud.githubusercontent.com/assets/405846/23325347/0023e0be-faf5-11e6-8dfe-d6196f9bda8c.png)
