### ISSUE TITLE
Wrong Port for Postgres Exporter

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry-community/prometheus-boshrelease#23]
According to the specs here: https://github.com/prometheus/prometheus/wiki/Default-port-allocations the Postgres Exporter exposes to 9187. Currently configured in prometheus-boshrelease we have 9113.

Is there any special reason why?

**Comment by frodenas** [comment]
Because 9113 is the real port used by default by the exporter: https://github.com/wrouesnel/postgres_exporter/blob/9143f5984afa69d55c7ef1efe8ecf13405d6bbda/postgres_exporter.go#L25 :confused:

I don't have any special preference, so feel free to submit a PR changing it to the one documented at the wiki.

**Comment by jhiemer** [comment]
@frodenas me neither. I just started the Postgres Exporter and saw that it is using 9187. So if you are fine with it, I will submit a PR.

**Comment by frodenas** [comment]
@jhiemer Sure, go ahead please.

**Comment by frodenas** [comment]
@jhiemer I just updated the default port to be `9187` (commit https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/df51dc898603d22076e1bcd1196a3f190c5e07ef). I'll cut a new release pretty soon.

**Comment by jhiemer** [comment]
@frodenas great. I have also created a deployment.yml for OpenStack and a complete setup for working exporters of CF, Bosh and Firehose. Based on that, I would create some documentation over the weekend and create a pull request, ok?

**Comment by frodenas** [comment]
Sounds good. Thanks.
