### ISSUE TITLE
Alerting on diego low remaining memory seems incorrect

### ISSUE THREAD

**Issue by ArthurHlt** [cloudfoundry-community/prometheus-boshrelease#24]
First, thank for the great work with release that's help a lot.

I have just an error with alerting, I have always a "DiegoLowRemainingMemory" alert on the alert manager. But I have 82 GB available in my cells as the Cf cells capacity dashboard says. This value on the dashboard seems actually correct as the query used to build this dashboard.

For me the alerting have a bad expression because as we can see here https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/src/cloudfoundry_alerts/diego.alerts#L26 it never does a sum with multiple cells we can have in a deployment. 

Am I wrong ? If no, I can propose this solution: `sum(avg(firehose_value_metric_rep_capacity_remaining_memory) by(bosh_deployment, bosh_job_name, bosh_job_id))` to replace the actual expression in the alert.

**Comment by frodenas** [comment]
Hi @ArthurHlt, 

Thanks for reporting this. You're right, some of the CF/Diego alerts are wrong and should be updated. It's on my todo list, but feel free to submit a PR fixing this issue if you're in a hurry.

**Comment by frodenas** [comment]
Fixed at #25
