### ISSUE TITLE
Interesting behaviour during upgrade

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry-community/prometheus-boshrelease#26]
Hi,
I did an extremely smooth upgrade from v239 to v245 of CF Release and Diego (according to specs of the CF Release) today. There were not errors the deployment went through.

I have to findings, which I would like to share and also discuss:
![screen shot 2017-01-06 at 11 16 47](https://cloud.githubusercontent.com/assets/1557826/21714976/1148a772-d402-11e6-8f4e-a5e3617beb2e.png)
I the picture above you can see, that the capacity decreased in this demo deployment although CF is running fine and we are still able to scale our sample application

![screen shot 2017-01-06 at 11 19 23](https://cloud.githubusercontent.com/assets/1557826/21715088/e2e96c1c-d402-11e6-9f0b-e8f060fd80fb.png)
The Compilation Workers are visible in the dashboard. Perhaps we should enable filtering on those for the dashboards?

**Comment by jhiemer** [comment]
Short reminder: forget about picture one. My two etcd instances were failing after the upgrade, had to restart them.

Now everything works fine again. So only question two remains, does it make sense to add a filter for those compilation workers?

**Comment by frodenas** [comment]
It might make sense, we already implemented that filter for alerts (https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/src/bosh_alerts/bosh_jobs.alerts#L2).
