### ISSUE TITLE
Scale-out

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry-community/prometheus-boshrelease#3]
As numbers of metrics ca be huge, for huge deployment how do we achieve scale-out architecture ?

Thanks

**Comment by frodenas** [comment]
Thanks for raising this issue @shinji62. HA, scalability, ... is something that it's on the backlog, but I don't want to focus on this yet, at least until I have a working and tuned environment on small deployments. I plan some breaking changes, when the release becomes more stable, then we can focus on the HA & scalability topics.

**Comment by frodenas** [comment]
We have successfully deployed a single prometheus instance on big environments (> 200vms and >25k apps) without any significant problem. For scale-out deployments, I recommend using the federation approach (see [Deployment Topology](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/docs/Deployment%20Topology.svg)).
