### ISSUE TITLE
Some metrics are missing

### ISSUE THREAD

**Issue by mjsjinsu** [cloudfoundry-community/prometheus-boshrelease#34]
Hi
I try to monitoring CF with prometheus-boshrelease 
currently I set up cf exporter, firehose exporter

Most metrics are collected with this exporter
but some metric were not show in prometheus DB

Ex)
firehose_counter_event_gorouter_bad_gateways_delta
firehose_counter_event_gorouter_bad_gateways_total
firehose_counter_event_gorouter_rejected_requests_delta
firehose_counter_event_gorouter_rejected_requests_total
firehose_counter_event_bbs_* metrics empty, except two metrics "firehose_counter_event_bbs_request_count_delta", "firehose_counter_event_bbs_request_count_total" 

ENV)
cf : 238
diego  : 0.1476.0

cf_exporter, version 0.4.3 (branch: master, revision: 9e37d9069bbb87d739d2c326981fed917ec016e4)
  build user:       root@1d21624a3782
  build date:       20170216-02:38:17
  go version:       go1.7.5

firehose_exporter, version 4.1.0 (branch: master, revision: 95333eab4c8295bf727faa564add32422f5d71c6)
  build user:       root@387dfcd86a81
  build date:       20170216-01:18:51
  go version:       go1.7.5

**Comment by frodenas** [comment]
Let's track this at https://github.com/cloudfoundry-community/firehose_exporter/issues/11.
