### ISSUE TITLE
Update Cloud Foundry alerts

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry-community/prometheus-boshrelease#39]
The [Cloud Foundry alerts](https://github.com/cloudfoundry-community/prometheus-boshrelease/tree/master/src/cloudfoundry_alerts) needs review & update.

**Comment by shinji62** [comment]
Could be based on https://docs.pivotal.io/pivotalcf/1-10/pcf-release-notes/runtime-rn.html

**Comment by frodenas** [comment]
CF Alerts have been moved to job templates, parametrized and refactored to match the KPIs: https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/c9f1b273561870bd2c06f670101653d3d5e0ccd6.
