### ISSUE TITLE
Prometheus data files stored under root partition

### ISSUE THREAD

**Issue by bobhlo** [cloudfoundry-community/prometheus-boshrelease#44]
Prometheus data files currently stored under root partition /var/vcap/store/prometheus and that can quickly cause root partition running out of disk space. Can we add an attribute to spec to override the attribute to point to data partition /var/vcap/data/prometheus?

It seems that storage.local.path is hardcoded to use /var/vcap/store/prometheus
https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/jobs/prometheus/templates/bin/prometheus_ctl#L90

**Comment by mkuratczyk** [comment]
Hi,

It's the other way round: /var/vcap/store should be the persistent disk mounted on your VM and should not be on your root partition. Unlike /var/vcap/data which is an ephemeral folder on the root partition. See here: https://bosh.io/docs/vm-config.html#storage

Have you attached a persistent disk to your Prometheus VM?

**Comment by bobhlo** [comment]
Thanks, the issue was resolved after a persistent disk created.
