### ISSUE TITLE
Bosh Dashboard and "All" deployment failed.

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry-community/prometheus-boshrelease#5]
Hi,

In grafana since v11 it seems that all bosh dashboard are failing.
Means when I select "All" jobs for example I got this error 
```
TypeError: Cannot read property 'replace' of undefined

```

**Comment by shinji62** [comment]
I think this is coming from this commit https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/2f82a98ff009522b53bed07fe9816ff77f7783b5

I removed the fix and now the dashboard is working correctly, I don't have so much time to look more deeper.

Thanks

**Comment by frodenas** [comment]
@shinji62 Do you mind providing me more info? I'm unable to reproduce your issue. Using v11, I'm able to see correctly all dashboards without any problems.

Was this an upgrade or a fresh deploy? Are you using the default grafana templates that came from the bosh release or are you using custom ones?

**Comment by mkuratczyk** [comment]
Same here - the dashboards work fine for me. The only thing "failing" (which I didn't notice before and I'm pretty sure wasn't there until recently) is that on the BOSH Overview dashboard, Jobs Health widget is red if all jobs are selected because it takes into consideration errands which are not running (the metric is 0 for them).

**Comment by shinji62** [comment]
@frodenas Seems that @mkuratczyk have the same trouble as me, everything works fine except when I select "all" job in the bosh dashboard.

I got this trouble since v11, and yes I use default bosh dashboard, provided by the release.
I don't have the error anymore, because I remove the code which I told you.

it's an upgrade, but I try to recreate the grafana jobs but result was the same.

**Comment by frodenas** [comment]
@shinji62 I have updated grafana to the latest beta (it contains the fix for some dashboards and also I want to test a possible UAA integration). I will cut a new release soon so you can test if it's working with that version.

**Comment by shinji62** [comment]
Ok, I will test it today if the release is cut.
I am still not sure how to use director deployed by opsmanager, I guess it use UAA.

I will poke around anyway.
Thanks

**Comment by frodenas** [comment]
I won't cut a new release until tomorrow, I need to test my latest fixes. @mkuratczyk (from Pivotal as well) can help you with the OpsMan/UAA, he has deployed it over PCF.

**Comment by shinji62** [comment]
Ok interesting! Thanks!

**Comment by mkuratczyk** [comment]
Take a look at my mini how-to: https://github.com/mkuratczyk/prometheus-on-PCF
I hope it helps.

**Comment by shinji62** [comment]
Works fine. Thanks
