### ISSUE TITLE
grafana v4.2.0 release

### ISSUE THREAD

**Issue by mjsjinsu** [cloudfoundry-community/prometheus-boshrelease#50]
Hi
Do you have a plan update of grafana job?
I think useful feature are merged

https://community.grafana.com/t/release-notes-for-grafana-v4-2-0/167

**Comment by frodenas** [comment]
Grafana has been upgraded to 4.2.0 (https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/c86815d0bce55f89e7eccbf4c17c8ee6a8a2c134). I'll cut a new release pretty soon.
