### ISSUE TITLE
firehose_exporter.metrics.environment values

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry-community/prometheus-boshrelease#59]
Hi,
currently trying to upgrade to 15.0.0 and was stopped by the following error:
```bash
Error 100: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'prometheus'. Errors are:
     - Unable to render templates for job 'bosh_exporter'. Errors are:
       - Error filling in template 'bosh_exporter_ctl' (line 76: Can't find property '["bosh_exporter.metrics.environment"]')
     - Unable to render templates for job 'firehose_exporter'. Errors are:
       - Error filling in template 'firehose_exporter_ctl' (line 70: Can't find property '["firehose_exporter.metrics.environment"]')
     - Unable to render templates for job 'cf_exporter'. Errors are:

```
Looking at the code at:

https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/589eb4e4292c1687910978d7330c0aed09d89444/jobs/firehose_exporter/templates/bin/firehose_exporter_ctl#L70

I see it is mandatory. Is this a mistake or intended behaviour? If so, what would be appropriate values for it?

**Comment by shinji62** [comment]
It's mandatory and exist since the previous release https://github.com/cloudfoundry-community/prometheus-boshrelease/tree/v14.0.0


You can have multiple env. send to the same prometheus so if free to you to input what you want.

**Comment by jhiemer** [comment]
@shinji62 that sounds great, so basically working towards managing multiple instance with one monitoring instance?

**Comment by shinji62** [comment]
well needs to differentiate.

**Comment by jhiemer** [comment]
k, thanks!
