### ISSUE TITLE
firehose_value_metric_etcd_is_leader duplicated

### ISSUE THREAD

**Issue by jriguera** [cloudfoundry-community/prometheus-boshrelease#63]
We are starting to have a look and test the prometheus boshrelease with 2 firehose exporters, Prometheus started to trigger one alert `CFEtcdMoreThanOneLeader (1 active)`:

```
ALERT CFEtcdMoreThanOneLeader
  IF count(firehose_value_metric_etcd_is_leader == 1) BY (environment, bosh_deployment) > 1
  FOR 10m
  LABELS {service="cf-etcd", severity="critical"}
  ANNOTATIONS {description="CF etcd cluster at deployment `{{$labels.environment}}/{{$labels.bosh_deployment}}` had more than one leader in the last 10 minutes: {{value}}", summary="CF etcd cluster at deployment `{{$labels.environment}}/{{$labels.bosh_deployment}}` > 1 leader"}
```
because there are two "similar" metrics. I have checked the status of the cluster and it is healthy, the leader is 10.230.16.79 (no partitions, only one leader).  In the next picture you can see the "same" metric was reported by a different Firehose instance at a different time (see  `instance` tag) so Prometheus considers these different metrics.

![image](https://cloud.githubusercontent.com/assets/1685104/25382657/e94d105c-29b8-11e7-9bf0-7467ad86d626.png)

I do not have enough experience with Prometheus, but, assuming that tagging the metric with the firehose_exporter instance is needed, where do you think this issue should be fixed: in the alert definition or doing some kind of "duplicates" deletion?  Any other ideas?

Thanks!

**Comment by frodenas** [comment]
Hi @jriguera. Thanks for reporting this. Yep, there're several alerts and dashboards that needs to be fixed when there're more than 1 nozzle deployed. I plan to fix them pretty soon.

**Comment by jriguera** [comment]
Hi @frodenas, nice! If I have enough time and if you tell me which approach you are thinking about to fix it, maybe I can work on it and send a PR

**Comment by frodenas** [comment]
@jriguera Sorry for the late reply, this has been fixed at https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/94ba65b89103232183ba2e7b524349b5238076ac and release version [v15.2.0](https://github.com/cloudfoundry-community/prometheus-boshrelease/releases/tag/v15.2.0).

There's no golden rule to deal with multiple instances of the same exporter. In this case, as you case see at the commit, it was just about counting by `instance` (that will return 2 samples) and then picking the `max` (even if there're 2 samples with the same value, it will return just 1 of them).
