### ISSUE TITLE
Grafana-UAA integration

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry-community/prometheus-boshrelease#7]
Create a document explaining how you can integrate Grafana user authentication with Cloud Foundry UAA.

**Comment by cppforlife** [comment]
@frodenas it would be nice to see what UAA should expose via a link so that it's automatically hooked up to Grafana.

**Comment by frodenas** [comment]
@cppforlife I'm not sure we are thinking about the same integration. On my mind, the integration will be using an external UAA for user management (ie reusing the same CF UAA instance so we will be log-in using regular CF users). In this case, I only need the external UAA oauth endpoint and a client-id and client-secret, not sure if links can help here. 

Is this the integration you're talking about? Or are you talking about a tighter integration like having a UAA instance just for Grafana?

**Comment by cppforlife** [comment]
@frodenas we are talking about the same integration. 

links are completely generic. you can link between deployment or external services. you could link grafana instance to cf uaa instance as long as uaa provide a uaa link (which it will eventually but it would be nice to understand what you would consume). at the least link can provide "UAA oauth endpoint " if not client credentials.

**Comment by frodenas** [comment]
The [enable-grafana-uaa.yml](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/manifests/operators/enable-grafana-uaa.yml) operation files allows setting up UAA for Grafana authentication.
