### ISSUE TITLE
Is anyone having issues with `label_values` in v17 Grafana?

### ISSUE THREAD

**Issue by dlapiduz** [cloudfoundry-community/prometheus-boshrelease#75]
Just upgraded to the 17.0.0 release and I am having a quite weird issue with Grafana.

If I keep the `label_values` in the template as is it doesn't return anything. If I change it to just use the label it works.

I ended up changing the dashboards to `label_values(environments)`.

Has anyone seen something like this?

**Comment by frodenas** [comment]
@dlapiduz Haven't seen this behavior in my environments. The `label_values` is still returning the `labels` for the provided `metric`.

**Comment by xanderrman** [comment]
@dlapiduz just checking in to see if this is still an issue, Thanks 👍

**Comment by frodenas** [comment]
Closing this, @dlapiduz please reopen if still persists.

**Comment by dlapiduz** [comment]
I haven't been using it lately so I am not sure if this is an issue but I will report back if I see something. Thanks!
