### ISSUE TITLE
Mysql Dashboard open source license type

### ISSUE THREAD

**Issue by mjsjinsu** [cloudfoundry-community/prometheus-boshrelease#77]
When `prometheus BOSH Release v17.0.0` released, All Dashboards file moved from packages to job templates. 
But `mysql dashboard` LICENSE file was removed. https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/d5abc49c4a6e635ba490269ebcd9b2416e4de488
What is open source license type of `mysql dashboard`?(Apache or AGPL-3.0)

**Comment by frodenas** [comment]
Good catch, It's AGPL. I planned to move it to the general NOTICE and I forget to add it. I'll add it again before cutting a new release.

**Comment by frodenas** [comment]
Fixed at https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/3f019e8ca3de2237c49a214fa38b9cc3b382cdad.
