### ISSUE TITLE
Bump elasticsearch_exporter again

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/prometheus-boshrelease#83]
Looks like 0.3.2 introduced a regression that was fixed in 0.3.3. Unfortunately, the regression causes the exporter to panic on `/metrics`, so it's basically unusable for now. Fix at https://github.com/justwatchcom/elasticsearch_exporter/pull/61.

**Comment by frodenas** [comment]
Bumped at https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/0658a6535ceba20d9a0c86692e872a86071d053f.
