### ISSUE TITLE
Fix Alert CFAuctioneerFetchStatesDurationTooHigh

### ISSUE THREAD

**Issue by Martin612** [cloudfoundry-community/prometheus-boshrelease#88]
Hello,

I'm using prometheus in an pivotal cloudfoundry environment and have an issue with the CFAuctioneerFetchStatesDurationTooHigh alert. 

This alert uses the AuctioneerFetchStatesDuration metric and divides  this metric by 1.000.000.
But this metric is measured in nanoseconds. Therefor it have to be divided by 1.000.000.000.
https://docs.pivotal.io/pivotalcf/1-11/monitoring/kpi.html#AuctioneerFetchStatesDuration

**Comment by frodenas** [comment]
Fixed at https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/db457302a332b54439a95a37d89e0fdb1aedf67a. Thanks!
