### ISSUE TITLE
Grafana Admin Passwort Update Failing

### ISSUE THREAD

**Issue by benjaminguttmann-avtq** [cloudfoundry-community/prometheus-boshrelease#91]
Hi,

we updated today from Prometheus v 17.0.0 to 17.5.0 and the deployment failed because of Grafana not successfully executing the post-script. 

```
Error: Failed to update user password
 
NAME:
   Grafana cli admin reset-admin-password - reset-admin-password <new password>
 
USAGE:
   Grafana cli admin reset-admin-password [command options] [arguments...]
 
OPTIONS:
   --homepath   path to grafana install/home path, defaults to working directory
   --config     path to config file
```

But to me the command executed seems correct. Any suggestions?

**Comment by frodenas** [comment]
Have you tried executing the command manually and see if it emits some more error details? Also, can you please check the grafana logs to see if there's any hint about why it failed?

**Comment by benjaminguttmann-avtq** [comment]
Sorry
