### ISSUE TITLE
CF Exporter - Filter Collector 

### ISSUE THREAD

**Issue by benjaminguttmann-avtq** [cloudfoundry-community/prometheus-boshrelease#96]
Hi,

I am facing currently an issue with the cf_exporter. 
When I define any collector mentioned in the specs of the exporter the export isn't able to start and shows errors like : 

time="2017-07-21T12:43:56Z" level=error msg="Collector filter `[ApplicationEvents]` is not supported" source="cf_exporter.go:213"

Any ideas?

Regards,

Benjamin

**Comment by mkuratczyk** [comment]
Hi,

ApplicationEvents collector has been removed in the recent version of cf_exporter: https://github.com/cloudfoundry-community/cf_exporter/commit/71922c528a1c5cfc12c8c113c48b655ce5c39242

**Comment by benjaminguttmann-avtq** [comment]
Hi,

thanks, this was just an example none of the mentioned Collectors actually works for me :-/

**Comment by frodenas** [comment]
@benjaminguttmann-avtq How are you setting the `cf_exporter.filter.collectors` property? Seems you're using an array (`[ApplicationEvents]`) and it should be a string (`Applications,ApplicationEvents,...`).

**Comment by frodenas** [comment]
@benjaminguttmann-avtq were you able to set up the collectors successfully?

**Comment by benjaminguttmann-avtq** [comment]
@frodenas , yes I was able to setup the collectors. I actually used a string but I used spaces between comma and word, that triggered the error :-/

**Comment by frodenas** [comment]
Thanks @benjaminguttmann-avtq.
